<a href="https://colab.research.google.com/github/daniellegaither/stock-markets-analytics-zoomcamp/blob/main/01-intro-and-data-sources/Module01_homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
# IMPORTS
import numpy as np
import pandas as pd

#Fin Data Sources
import yfinance as yf
import pandas_datareader as pdr

#Data viz
import plotly.graph_objs as go
import plotly.express as px

import time
from datetime import date

Question 1: [Macro] Average growth of GDP in 2023
What is the average growth (in %) of GDP in 2023?

Download the timeseries Real Gross Domestic Product (GDPC1) from FRED (https://fred.stlouisfed.org/series/GDPC1). Calculate year-over-year (YoY) growth rate (that is, divide current value to one 4 quarters ago). Find the average YoY growth in 2023 (average from 4 YoY numbers). Round to 1 digit after the decimal point: e.g. if you get 5.66% growth => you should answer 5.7

In [31]:
gdpc1_start = date(year=2022, month=1, day=1)
gdpc1_end = date(year=2023, month=12, day=31)
print(f'Period for indexes: {gdpc1_start} to {gdpc1_end} ')
# gdppot = pdr.DataReader("GDPPOT", "fred", start, end)
# gdppot.tail()
gdpc1 = pdr.DataReader("GDPC1", "fred", gdpc1_start, gdpc1_end)
gdpc1.tail()

Period for indexes: 2022-01-01 to 2023-12-31

                GDPC1
DATE
2022-10-01  21989.981
2023-01-01  22112.329
2023-04-01  22225.350
2023-07-01  22490.692
2023-10-01  22679.255

In [32]:
"""gdppot['gdppot_us_yoy'] = gdppot.GDPPOT/gdppot.GDPPOT.shift(4) - 1
gdppot['gdppot_us_qoq'] = gdppot.GDPPOT/gdppot.GDPPOT.shift(4)-1
gdppot.tail()"""
gdpc1['gdcp1_us_yoy'] = gdpc1.GDPC1/gdpc1.GDPC1.shift(4) - 1
gdpc1.tail()
relevant_quarters = gdpc1['gdcp1_us_yoy'].tail(4)
print('Average GDP growth for 2023:')
print(f"{relevant_quarters.mean():.1%}")

Average GDP growth for 2023:
2.5%

Question 2. [Macro] Inverse "Treasury Yield"
Find the min value of (dgs10-dgs2) after since year 2000 (2000-01-01) and write it down as an answer, round to 1 digit after the decimal point.

Download DGS2 and DGS10 interest rates series (https://fred.stlouisfed.org/series/DGS2, https://fred.stlouisfed.org/series/DGS10). Join them together to one dataframe on date (you might need to read about pandas.DataFrame.join()), calculate the difference dgs10-dgs2 daily.

(Additional: think about what does the "inverted yield curve" mean for the market and investors? do you see the same thing in your country/market of interest? Do you think it can be a good predictive feature for the models?)

In [33]:
dgs_start = date(2000, 1, 1)
dgs_end = date.today()
dgs2 = pdr.DataReader("DGS2", "fred", dgs_start, dgs_end)
dgs2.tail()

            DGS2
DATE
2024-04-16  4.97
2024-04-17  4.93
2024-04-18  4.98
2024-04-19  4.97
2024-04-22  4.97

In [34]:
dgs10 = pdr.DataReader("DGS10", "fred", dgs_start, dgs_end)
dgs10.tail()

            DGS10
DATE
2024-04-16   4.67
2024-04-17   4.59
2024-04-18   4.64
2024-04-19   4.62
2024-04-22   4.62

In [35]:
dgs_combined = dgs2.join(dgs10)
dgs_combined.tail()

            DGS2  DGS10
DATE
2024-04-16  4.97   4.67
2024-04-17  4.93   4.59
2024-04-18  4.98   4.64
2024-04-19  4.97   4.62
2024-04-22  4.97   4.62

In [36]:
dgs_combined["inverted_yield"] = dgs_combined['DGS10'] - dgs_combined['DGS2']
print("Minimum inverted yield value:", round(dgs_combined["inverted_yield"].min(), 1))

Minimum inverted yield value: -1.1

Question 3. [Index] Which Index is better recently?
Compare S&P 500 and IPC Mexico indexes by the 5 year growth and write down the largest value as an answer (%)

Download on Yahoo Finance two daily index prices for S&P 500 (^GSPC, https://finance.yahoo.com/quote/%5EGSPC/) and IPC Mexico (^MXX, https://finance.yahoo.com/quote/%5EMXX/). Compare 5Y growth for both (between 2019-04-09 and 2024-04-09). Select the higher growing index and write down the growth in % (closest integer %). E.g. if ratio end/start was 2.0925 (or growth of 109.25%), you need to write down 109 as your answer.

(Additional: think of other indexes and try to download stats and compare the growth? Do create 10Y and 20Y growth stats. What is an average yearly growth rate (CAGR) for each of the indexes you select?)

In [45]:
start = date(2019, 4, 9)
end = date(2024, 4, 9)
spx_index = pdr.get_data_stooq('^SPX', start, end)
spx_index.tail()

               Open     High      Low    Close        Volume
Date
2019-04-15  2908.32  2909.60  2896.48  2905.58  1.715739e+09
2019-04-12  2900.86  2910.54  2898.37  2907.41  2.049161e+09
2019-04-11  2891.92  2893.42  2881.99  2888.32  1.632522e+09
2019-04-10  2881.37  2889.71  2879.13  2888.21  1.701322e+09
2019-04-09  2886.58  2886.88  2873.33  2878.20  1.671100e+09

In [39]:
mxx_index = yf.download("^MXX", start, '2024-04-10')
mxx_index.tail()

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-04-03,57547.191406,58086.421875,57300.109375,57503.390625,57503.390625,189285300
2024-04-04,57539.468750,58219.500000,57514.179688,57882.761719,57882.761719,184739700
2024-04-05,57805.191406,58227.839844,57678.609375,58092.441406,58092.441406,212252300
2024-04-08,58021.660156,58192.320312,57749.441406,57989.941406,57989.941406,154641800
2024-04-09,58010.371094,58298.769531,57492.058594,57571.148438,57571.148438,202213300

In [41]:
mxx_index.head()

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2019-04-09,45346.828125,45346.828125,44854.531250,45151.628906,45151.628906,191575000
2019-04-10,45204.750000,45219.410156,44850.109375,44909.140625,44909.140625,145314900
2019-04-11,44872.531250,44966.500000,44373.488281,44580.058594,44580.058594,109090000
2019-04-12,44767.671875,44888.699219,44534.378906,44686.058594,44686.058594,143662400
2019-04-15,44649.738281,44900.929688,44347.531250,44625.781250,44625.781250,108627100

In [56]:
spx_index_ratio = spx_index['Close'][0]/spx_index['Close'][-1]
print('S&P 500 growth ratio:')
print(f"{spx_index_ratio - 1:.0%}")

S&P 500 growth ratio:
81%

In [55]:
mxx_index_ratio = mxx_index['Close'][-1]/mxx_index['Close'][0]
print('MXX growth ratio:')
print(f"{mxx_index_ratio - 1:.0%}")

MXX growth ratio:
28%

Question 4. [Stocks OHLCV] 52-weeks range ratio (2023) for the selected stocks
Find the largest range ratio [=(max-min)/max] of Adj.Close prices in 2023

Download the 2023 daily OHLCV data on Yahoo Finance for top6 stocks on earnings (https://companiesmarketcap.com/most-profitable-companies/): 2222.SR,BRK-B, AAPL, MSFT, GOOG, JPM.

Here is the example data you should see in Pandas for "2222.SR": https://finance.yahoo.com/quote/2222.SR/history

Calculate maximum-minimim "Adj.Close" price for each stock and divide it by the maximum "Adj.Close" value. Round the result to two decimal places (e.g. 0.1575 will be 0.16)

(Additional: why this may be important for your research?)

In [70]:
start = date(2023, 1, 1)
end = date(2023, 12, 31)
big6 = yf.download("2222.SR BRK-B AAPL MSFT GOOG JPM", start, end)
big6['Adj Close'].tail()

[*********************100%%**********************]  6 of 6 completed

Ticker,2222.SR,AAPL,BRK-B,GOOG,JPM,MSFT
Date,,,,,,
2023-12-25,32.927525,NaN,NaN,NaN,NaN,NaN
2023-12-26,32.877789,192.803986,356.829987,142.820007,166.387451,373.968445
2023-12-27,32.977268,192.903839,356.950012,141.440002,167.385437,373.379547
2023-12-28,32.877789,193.333298,357.570007,141.279999,168.274734,374.587280
2023-12-29,NaN,192.284637,356.660004,140.929993,168.077118,375.345886

In [68]:
sr22_ratio = (big6['Adj Close']['2222.SR'].max() - big6['Adj Close']['2222.SR'].min()) / big6['Adj Close']['2222.SR'].max()
brkb_ratio = (big6['Adj Close']['BRK-B'].max() - big6['Adj Close']['BRK-B'].min()) / big6['Adj Close']['BRK-B'].max()
aapl_ratio = (big6['Adj Close']['AAPL'].max() - big6['Adj Close']['AAPL'].min()) / big6['Adj Close']['AAPL'].max()
msft_ratio = (big6['Adj Close']['MSFT'].max() - big6['Adj Close']['MSFT'].min()) / big6['Adj Close']['MSFT'].max()
goog_ratio = (big6['Adj Close']['GOOG'].max() - big6['Adj Close']['GOOG'].min()) / big6['Adj Close']['GOOG'].max()
jpm_ratio = (big6['Adj Close']['JPM'].max() - big6['Adj Close']['JPM'].min()) / big6['Adj Close']['JPM'].max()
max_ratio = max(sr22_ratio, brkb_ratio, aapl_ratio, msft_ratio, goog_ratio, jpm_ratio)
print(f"52-week range ratio: {round(max_ratio, 2)}")

52-week range ratio: 0.42

Question 5. [Stocks] Dividend Yield
Find the largest dividend yield for the same set of stocks

Use the same list of companies (2222.SR,BRK-B, AAPL, MSFT, GOOG, JPM) and download all dividends paid in 2023. You can use get_actions() method or .dividends field in yfinance library (https://github.com/ranaroussi/yfinance?tab=readme-ov-file#quick-start)

Sum up all dividends paid in 2023 per company and divide each value by the closing price (Adj.Close) at the last trading day of the year.

Find the maximum value in % and round to 1 digit after the decimal point. (E.g., if you obtained \$1.25 dividends paid and the end year stock price is $100, the dividend yield is 1.25% -- and your answer should be equal to 1.3)

In [83]:
tickers = yf.Tickers("2222.SR BRK-B AAPL MSFT GOOG JPM")

dict_keys(['2222.SR', 'BRK-B', 'AAPL', 'MSFT', 'GOOG', 'JPM'])

In [84]:
sr22_dividends = tickers.tickers['2222.SR'].dividends
sr22_dividends.tail()

Date
2023-03-15 00:00:00+03:00    0.302364
2023-05-17 00:00:00+03:00    0.302400
2023-09-11 00:00:00+03:00    0.153000
2023-11-15 00:00:00+03:00    0.153000
2024-03-14 00:00:00+03:00    0.167000
Name: Dividends, dtype: float64

Question 6. [Exploratory] Investigate new metrics
Free text answer

Download and explore a few additional metrics or time series that might be valuable for your project and write down why (briefly).

Question 7. [Exploratory] Time-driven strategy description around earnings releases
Free text answer

Explore earning dates for the whole month of April - e.g. using YahooFinance earnings calendar (https://finance.yahoo.com/calendar/earnings?from=2024-04-21&to=2024-04-27&day=2024-04-23). Compare with the previous closed earnings (e.g., recent dates with full data https://finance.yahoo.com/calendar/earnings?from=2024-04-07&to=2024-04-13&day=2024-04-08).

Describe an analytical strategy/idea (you're not required to implement it) to select a subset companies of interest based on the future events data.